language: node_js
node_js:
- stable
script:
  - npm run build
cache:
  directories:
    - "node_modules"
after_success:
- bash ./deploy.sh
deploy:
- provider: azure_web_apps
  slot: dronecompanionapp
  on: master
- provider: azure_web_apps
  slot: dronecompanionapp-acc
  on: stable
- provider: azure_web_apps
  slot: dronecompanionapp-dev
  on: develop

   